---
all:
  children:
    molecule:
      hosts:
        molecule-debian:
          ansible_connection: containers.podman.podman
          container_image: docker.io/geerlingguy/docker-debian13-ansible:latest
          container_command: sleep 1d
          container_privileged: false
