- name: Converge
  hosts: all
  gather_facts: true
  vars:
    aptrepo_apt_key_url: "https://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key"
    aptrepo_apt_key_file: "hwraid.le-vert.net.gpg"
    aptrepo_apt_repository: "http://hwraid.le-vert.net/debian"
    aptrepo_apt_release: "{{ ansible_distribution_release }}"
    aptrepo_apt_component: "main"
    aptrepo_apt_sources_file: "hwraid.list"

  roles:
    - role: jkirk.aptrepo

  tasks:
    - name: Ensure megacli package is installed
      apt:
        name: megacli
